version: "3.8"

networks:
  spark_network:
    driver: bridge

services:
  docs:
    container_name: docs
    image: nginx
    ports:
      - "127.0.0.1:90:80"  # Restrict to localhost
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"
    networks:
      - spark_network

  master:
    container_name: master
    image: bitnami/spark:3.2.1
    restart: always
    command: ["/opt/bitnami/spark/sbin/start-master.sh"]
    environment:
      MASTER: ${SPARK_MASTER_URL}
      SPARK_HOME: /opt/bitnami/spark
      SPARK_NO_DAEMONIZE: 1
    ports:
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:6066:6066"
      - "127.0.0.1:7077:7077"
      - "127.0.0.1:9090:8080"
    volumes:
      - ./code:/app
      - ./dataset:/dataset
    networks:
      - spark_network

  worker1:
    container_name: worker1
    image: bitnami/spark:3.2.1
    restart: always
    command: ["/opt/bitnami/spark/sbin/start-slave.sh", "${SPARK_MASTER_URL}"]
    environment:
      MASTER: ${SPARK_MASTER_URL}
      SPARK_NO_DAEMONIZE: 1
    depends_on:
      - master
    ports:
      - "127.0.0.1:4041:4040"
    volumes:
      - ./code:/app
      - ./dataset:/dataset
    networks:
      - spark_network

  worker2:
    container_name: worker2
    image: bitnami/spark:3.2.1
    restart: always
    command: ["/opt/bitnami/spark/sbin/start-slave.sh", "${SPARK_MASTER_URL}"]
    environment:
      MASTER: ${SPARK_MASTER_URL}
      SPARK_NO_DAEMONIZE: 1
    depends_on:
      - master
    ports:
      - "127.0.0.1:4042:4040"
    volumes:
      - ./code:/app
      - ./dataset:/dataset
    networks:
      - spark_network

  jupyter:
    container_name: jupyter
    image: jupyter/pyspark-notebook
    restart: always
    environment:
      MASTER: ${SPARK_MASTER_URL}
    depends_on:
      - master
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./jupyter/notebook:/notebook
      - ./dataset:/dataset
      - ./code:/app
    networks:
      - spark_network

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    networks:
      - spark_network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - 9092
    ports:
      - "127.0.0.1:9093:9092"
    networks:
      - spark_network
